# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api-container
        # *** IMPORTANT CHANGE HERE ***
        image: gcr.io/workoutvideos/iris-api:v1.0.1  # <<< CHANGE THIS to your correct project ID
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
